[35;21m2023-11-20 17:38:56,523 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): sent 1011 (internal error) keepalive ping timeout; no close frame received[0m
[35;21m2023-11-20 17:38:59,559 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): sent 1011 (internal error) keepalive ping timeout; no close frame received[0m
[35;21m2023-11-20 17:51:59,495 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (MuException): H5 writing process failed: Unable to synchronously create group (invalid identifier type to function). Stop running.[0m
[35;21m2023-11-20 17:51:59,606 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:300): Halt failed: Halt command failed on remote server: There is no listener job or run job to halt[0m
[35;21m2023-11-20 17:58:06,110 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): sent 1011 (internal error) keepalive ping timeout; no close frame received[0m
